/*
Il computer deve generare 16 numeri casuali tra 1 e 100.
I numeri non possono essere duplicati (tadaaa!)
In seguito deve chiedere all’utente (100 - 16) volte di inserire un numero alla volta, sempre compreso tra 1 e 100.
L’utente non può inserire più volte lo stesso numero.
Se il numero è presente nella lista dei numeri generati, la partita termina, altrimenti si continua chiedendo all’utente un altro numero.
La partita termina quando il giocatore inserisce un numero “vietato” o raggiunge il numero massimo possibile di numeri consentiti.
Al termine della partita il software deve comunicare il punteggio, cioè il numero di volte che l’utente ha inserito un numero consentito.
*/

// 1: 16 between 100 numbers randomly generated by computer

var bombsList = []; //empty array

function randomNums(min, max) { //ranged random numbers function
  var result = Math.floor(Math.random() * (max - min + 1)) + min;
  return result;
}

// Il computer deve generare 16 numeri casuali tra 1 e 100.
// I numeri non possono essere duplicati (tadaaa!)

function array(list, element) {
  var present = false;

  for (var i = 0; i < list.length; i++) {
    if (list[i] === element) {
      present = true;
    }
  }
  return present;
}

while (bombsList.length < 16) {
  var randomNum = randomNums(1, 100);

  if (array(bombsList, randomNum) === false) {
    bombsList.push(randomNum);
  }
}
bombsList.sort(function(a, b){return a-b});
console.log(bombsList);

// Chiedere all’utente (100 - 16) per 84 volte di inserire un numero alla volta, sempre compreso tra 1 e 100.
var maxNumber = 100;
var userChosenNumbers = [];
var userNumber = parseInt(prompt("Inserisci un numero tra 1 e " + maxNumber));

do {
  if (userNumber <= 0) {
    alert('You cannot enter a number less than 1. Try again');
  } else if (userNumber > maxNumber) {
    alert('You cannot enter a number more than ' + maxNumber + '. Try again');
  } else if (isNaN(userNumber)) {
    alert('You cannot enter a word or any other special character')
  }

} while (userNumber <= 0 || userNumber > maxNumber || isNaN(userNumber));



var verifyUserNum = isPresent(userNumber, userChosenNumbers);

if (verifyUserNum === false) {
  userChosenNumbers.push(userNumber);
} else if (verifyUserNum === true) {
  alert('You have already entered this number!')
}

for (var b = 0; b < bombsList.length; b++) {
  if (userNumber === bombsList[b]) {
    alert('KABOOM!\nThe Number ' + userNumber + ' is a bomb!\nYou lose.')
  }
}


function isPresent(par1, par2) {
  var result = false;

  for (var p = 0; p < par2.length; p++) {
    if (par1 === par2[p]) {
      result === true;
    }
    return result;
  }
}
console.log(userNumber);
