/*
Il computer deve generare 16 numeri casuali tra 1 e 100.
I numeri non possono essere duplicati (tadaaa!)
In seguito deve chiedere all’utente (100 - 16) volte di inserire un numero alla volta, sempre compreso tra 1 e 100.
L’utente non può inserire più volte lo stesso numero.
Se il numero è presente nella lista dei numeri generati, la partita termina, altrimenti si continua chiedendo all’utente un altro numero.
La partita termina quando il giocatore inserisce un numero “vietato” o raggiunge il numero massimo possibile di numeri consentiti.
Al termine della partita il software deve comunicare il punteggio, cioè il numero di volte che l’utente ha inserito un numero consentito.
*/

// 1: 16 between 100 numbers randomly generated by computer

var bombsList = []; //empty array

function randomNums(min, max) { //ranged random numbers function
  var result = Math.floor(Math.random() * (max - min + 1)) + min;
  return result;

}

// Il computer deve generare 16 numeri casuali tra 1 e 100.
// I numeri non possono essere duplicati (tadaaa!)

function array(list, element) {
  var present = false;

  for (var i = 0; i < list.length; i++) {
    if (list[i] === element) {
      present = true;
    }
  }
  return present;

}

while (bombsList.length < 16) {
  var randomNum = randomNums(1, 100);

  if (array(bombsList, randomNum) === false) {
    bombsList.push(randomNum);
  }
}
bombsList.sort(function(a, b){return a-b});
console.log(bombsList);
